package main

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	"github.com/marema31/tirith/controllers"
	_ "github.com/marema31/tirith/docs" // docs is generated by Swag CLI
	"github.com/marema31/tirith/models"
)

// @title Tirith
// @version 1.0
// @description Playground application for learning go, gin framework and several deployment options.
// @termsOfService http://swagger.io/terms/

// @contact.name Marema31
// @contact.url https://github.com/marema31
// @contact.email marema31t@github.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @BasePath /
func main() {
	r := gin.Default()
	if err := models.ConnectDatabase(); err != nil {
		panic(err)
	}
	controllers.Register(r)

	//	url := ginSwagger.URL("/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	if err := r.Run(); err != nil {
		panic(err)
	}
}
